### ISSUE TITLE
button Unfold  transform to toggle fold - unfold

### ISSUE THREAD

**Issue by xibman** [phossa/smartselect#7]
I think it could be usefull the unfold button can be use as a toggle ( fold, unfold)

**Comment by phossa** [comment]
the view button (the eye icon) serves as the 'fold' button but also shows the selected options. if you think it is not ok, i can add the fold/unfold toggle.

**Comment by xibman** [comment]
you're Right it's good with the current state !

**Comment by phossa** [comment]
I added a new option 'enableCollapseAll' in 1.0.23 version. You may check it out. Also I finally get time to look at your code regarding noSelectable. I just can not figure out how it works. Can you give me an example ?

**Comment by phossa** [comment]
Also PLEASE star this project if you can :)
