### ISSUE TITLE
Cascade down  when selecting parent node

### ISSUE THREAD

**Issue by xibman** [phossa/smartselect#8]
HI  @phossa 

is'it possible to cascade down selection when i  select a parent node ?

**Comment by phossa** [comment]
as i can recall, the design of this plugin is that selecting the parent means select all of its descendant nodes (but without showing the check before each child node). this is easier for calculating the selected values :). 
Also no half selected icon/status for the parent node to indicate some of the child nodes are selected.  but this is a easy feature if everyone wants it :) ican add this.
