### ISSUE TITLE
remove all options

### ISSUE THREAD

**Issue by sodayg** [phossa/smartselect#9]
hi. great plugin
is there a way to remove all options and not one by one? when i have a lot of options the process of deleting all of them is a bit too slow
thanks

**Comment by phossa** [comment]
hmm. Just out of curiosity, why do you want to remove all options ? I would suggest first empty your HTML select then rebuild (create) a new plugin base on this new HTML SELECT. If this does not help, I will look at the code and find another simple way.

**Comment by sodayg** [comment]
i'm working with an instance of the plugin and i use the plugin in 3 places on my page with diferent instances. when i empty the html and create the plugin - the instance remember the old options.
what am i doing wrong?

**Comment by phossa** [comment]
I just released a new version 1.0.24 with a new public method clearAllOptions(). The demo and doc html page are updated.
